enemies = {
    1: {
        "name": "Mucha (LVL 1)",
        "Strength": 3,
        "Defense": 1,
        "Dexterity": 2,
        "Skill": 2,
        "Luck": 1,
        "HP": 25,
    },
    2: {
        "name": "Dracek mracek (LVL 2)",
        "Strength": 4,
        "Defense": 3,
        "Dexterity": 1,
        "Skill": 2,
        "Luck": 1,
        "HP": 35,
    },
    3: {
        "name": "Baron (LVL 3)",
        "Strength": 4,
        "Defense": 4,
        "Dexterity": 2,
        "Skill": 3,
        "Luck": 5,
        "HP": 50,
    },
    4: {
        "name": "Ferko (LVL 4)",
        "Strength": 7,
        "Defense": 7,
        "Dexterity": 5,
        "Skill": 5,
        "Luck": 1,
        "HP": 70,
    },
    5: {
        "name": "Boris - buh smradlych penachymu (LVL 5)",
        "Strength": 7,
        "Defense": 7,
        "Dexterity": 7,
        "Skill": 1,
        "Luck": 7,
        "HP": 100,
    },
}
